apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
      - image: docker pull raymix11/todo-client-kubernetes-app:latest
        name: container1
        env:
        - name: REACT_APP_baseAPIURL
          value: "http://a66bdd7f09ac24de186ac36f3f86b3d7-1210016368.us-west-2.elb.amazonaws.com:5000"
        command: ["npm","start"]
        imagePullPolicy: Always
        ports:
          - containerPort: 3000